#!/bin/bash

# Installs zj-58 driver
# Tested as working under Ubuntu 14.04

systemctl stop cups
cp rastertozj /usr/lib/cups/filter/
mkdir -p /usr/share/cups/model/zjiang
cp ZJ-58.ppd /usr/share/cups/model/zjiang/
cd /usr/lib/cups/filter
chmod 755 rastertozj
chown root:root rastertozj
cd -
systemctl start cups
